(function(){
var currentFilter='all',currentQuery='';
function normalize(s){return(s||'').toLowerCase().replace(/ё/g,'е').replace(/[^a-zа-я0-9\s]/gi,' ').replace(/\s+/g,' ').trim()}
var synonyms={'передать':['отправить','перекинуть','скинуть','share','airdrop','localsend','файл','фото'],'файл':['фото','видео','документ','картинка'],'два':['клонирование','dual','parallel','второй','аккаунт','клон'],'whatsapp':['ватсап','вацап','вотсап'],'телеграм':['telegram','тг'],'split':['разделённый','два окна','многозадачность'],'dex':['desktop','рабочий стол','монитор','пк','компьютер'],'зарядка':['заряд','powershare','обратная'],'бэкап':['backup','резерв','копия','перенос'],'sideload':['ipa','app store','altstore','установка'],'яркость':['автояркость','brightness','экран'],'samsung':['самсунг','galaxy'],'xiaomi':['сяоми','redmi','poco','hyperos'],'iphone':['айфон','apple'],'ускорить':['тормозит','медленно','оптимизация','лаг'],'пароль':['password','менеджер'],'vpn':['впн']};
function expandQuery(q){var words=normalize(q).split(' ').filter(Boolean),extra=[];words.forEach(function(w){Object.keys(synonyms).forEach(function(k){if(w.indexOf(k)!==-1||k.indexOf(w)!==-1)synonyms[k].forEach(function(s){extra.push(s)})})});return Array.from(new Set(words.concat(extra)))}
function scoreItem(item,query){if(!query)return 1;var words=expandQuery(query);if(!words.length)return 1;var title=normalize(item.title),desc=normalize(item.desc),tags=(item.tags||[]).map(normalize).join(' '),sol=normalize((item.solution||'').replace(/<[^>]+>/g,' ')),brand=normalize(item.brand||''),score=0;words.forEach(function(w){if(title.indexOf(w)!==-1)score+=15;if(tags.indexOf(w)!==-1)score+=11;if(brand.indexOf(w)!==-1)score+=10;if(desc.indexOf(w)!==-1)score+=5;if(sol.indexOf(w)!==-1)score+=2});return score}
function getFiltered(){var list=(typeof knowledge!=='undefined'?knowledge.slice():[]);if(currentFilter!=='all')list=list.filter(function(i){return i.platform===currentFilter});if(currentQuery.trim())list=list.map(function(i){return{item:i,score:scoreItem(i,currentQuery)}}).filter(function(x){return x.score>0}).sort(function(a,b){return b.score-a.score}).map(function(x){return x.item});return list}
function render(){var list=getFiltered(),c=document.getElementById('content'),info=document.getElementById('results-info');if(!c||!info)return;if(!list.length){c.innerHTML='<div class="feature"><p class="desc">Пока нет точного совпадения. Попробуй другими словами или выбери фильтр. Пример: «два WhatsApp», «передать файл», «DeX», «ускорить телефон».</p></div>';info.textContent='Ничего не найдено';return}info.textContent=currentQuery.trim()?'Найдено: '+list.length+' · «'+currentQuery+'»':'Показано: '+list.length;c.innerHTML=list.map(function(item){return'<div class="feature"><h2>'+item.title+' <span class="badge possible">'+(item.statusText||'Можно')+'</span> <span class="badge platform">'+(item.platform||'').toUpperCase()+'</span></h2><p class="desc">'+(item.desc||'')+'</p><div class="solution">'+(item.solution||'')+'</div></div>'}).join('')}
function doSearch(){var i=document.getElementById('searchInput');if(i)currentQuery=i.value;render()}
function setFilter(p){currentFilter=p;document.querySelectorAll('.filter-btn').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-platform')===p)});render()}
var input=document.getElementById('searchInput'),btn=document.getElementById('searchBtn');if(btn)btn.addEventListener('click',doSearch);if(input){input.addEventListener('keydown',function(e){if(e.key==='Enter')doSearch()});input.addEventListener('input',function(){clearTimeout(window._t);window._t=setTimeout(function(){currentQuery=input.value;render()},150)})}document.querySelectorAll('.filter-btn').forEach(function(b){b.addEventListener('click',function(){setFilter(b.getAttribute('data-platform'))})});if(typeof knowledge==='undefined'){document.getElementById('content').innerHTML='<div class="feature"><p class="desc">Обнови страницу (Ctrl+F5).</p></div>'}else render()
})();