const knowledge = [
  // ===== iOS =====
  {id:1,platform:"ios",tags:["sideload","ipa","app store","altstore","trollstore","установка приложения"],title:"Установка приложений вне App Store (Sideloading)",status:"partial",statusText:"Частично",desc:"Apple ограничивает установку вне App Store.",solution:`<strong>AltStore</strong><ul><li>Скачай AltServer с altstore.io</li><li>Подключи iPhone кабелем, установи AltStore</li><li>Ставь .ipa через AltStore (обновлять раз в 7 дней)</li></ul><strong>TrollStore</strong> — на поддерживаемых iOS без срока. <strong>ЕС</strong> — сторонние магазины с iOS 17.4+.`},
  {id:2,platform:"ios",tags:["split screen","разделённый экран","ipad","многозадачность"],title:"Разделённый экран (Split View)",status:"partial",statusText:"Только iPad",desc:"На iPhone нет, на iPad есть.",solution:`iPad: Dock → перетащи второе приложение к краю. Или Stage Manager в Настройках → Многозадачность.`},
  {id:3,platform:"ios",tags:["обратная зарядка","powershare"],title:"Обратная беспроводная зарядка",status:"impossible",statusText:"Невозможно",desc:"iPhone не отдаёт зарядку.",solution:`Только внешний MagSafe-пауэрбанк или обычный powerbank.`},
  {id:4,platform:"ios",tags:["desktop","stage manager","монитор"],title:"Режим рабочего стола",status:"partial",statusText:"Только iPad",desc:"iPhone не умеет, iPad — через Stage Manager.",solution:`Подключи монитор + включи Stage Manager.`},
  {id:5,platform:"ios",tags:["два аккаунта","клонирование","whatsapp","telegram"],title:"Два аккаунта / клонирование приложений",status:"partial",statusText:"Частично",desc:"Нативного Dual Apps нет.",solution:`Telegram — несколько аккаунтов официально. Остальное — веб-версия + На экран Домой.`},
  {id:6,platform:"ios",tags:["гость","guided access"],title:"Гостевой режим",status:"impossible",statusText:"Невозможно",desc:"Нескольких пользователей нет.",solution:`Guided Access или Screen Time.`},
  {id:7,platform:"ios",tags:["файлы","файловая система"],title:"Доступ к файлам",status:"partial",statusText:"Частично",desc:"Песочница приложений.",solution:`Приложение «Файлы» + облака. Полный доступ — только jailbreak.`},
  {id:8,platform:"ios",tags:["громкость","звук"],title:"Регуляторы громкости",status:"possible",statusText:"Есть",desc:"В новых iOS гибче.",solution:`Настройки → Звуки и тактильные сигналы.`},
  {id:9,platform:"ios",tags:["apple pay","nfc","россия","оплата"],title:"Apple Pay / NFC в России",status:"impossible",statusText:"Не работает",desc:"С российскими картами не работает.",solution:`QR-оплата, Mir Pay на Android.`},
  {id:10,platform:"ios",tags:["airdrop","передать файл"],title:"AirDrop",status:"possible",statusText:"Есть",desc:"Быстрая передача между Apple.",solution:`Пункт управления → AirDrop → Все/Контакты. Wi-Fi и Bluetooth включены.`},

  // ===== Android =====
  {id:20,platform:"android",tags:["quick share","airdrop","передать файл","localsend"],title:"Быстрая передача файлов",status:"possible",statusText:"Есть",desc:"Несколько способов.",solution:`Quick Share в настройках Google. Лучше всего — LocalSend (localsend.org) для любых устройств.`},
  {id:21,platform:"android",tags:["rcs","сообщения","imessage"],title:"RCS / сообщения",status:"partial",statusText:"Частично",desc:"Зависит от оператора.",solution:`Google Messages → Чат-функции → RCS.`},
  {id:22,platform:"android",tags:["lidar","3d"],title:"LiDAR",status:"impossible",statusText:"Невозможно",desc:"Нет физического LiDAR.",solution:`ToF + приложения Measure / AR Ruler.`},
  {id:23,platform:"android",tags:["uwb","airtag","трекер"],title:"UWB Precision Finding",status:"partial",statusText:"Флагманы",desc:"Только на части устройств.",solution:`Pixel Pro, Galaxy S Ultra и некоторые другие. SmartTag+, Moto Tag.`},
  {id:24,platform:"android",tags:["now bar","dynamic island","live"],title:"Live Activities / Now Bar",status:"partial",statusText:"Частично",desc:"Есть у производителей.",solution:`Samsung Now Bar, Pixel At a Glance.`},
  {id:25,platform:"android",tags:["бэкап","backup","smart switch","перенос"],title:"Бэкап и перенос данных",status:"partial",statusText:"Частично",desc:"Лучше, чем раньше.",solution:`Samsung Smart Switch, Google Backup, Mi Mover.`},
  {id:26,platform:"android",tags:["dual app","клонирование","два whatsapp","два аккаунта"],title:"Клонирование приложений",status:"possible",statusText:"Есть",desc:"На большинстве Android.",solution:`Samsung Dual Messenger, Xiaomi Dual Apps, Parallel Space, Island.`},
  {id:27,platform:"android",tags:["гость","пользователи"],title:"Гостевой режим",status:"possible",statusText:"Есть",desc:"Есть почти везде.",solution:`Настройки → Система → Несколько пользователей.`},
  {id:28,platform:"android",tags:["обратная зарядка","powershare"],title:"Обратная беспроводная зарядка",status:"partial",statusText:"Многие флагманы",desc:"Samsung, Xiaomi, OnePlus и др.",solution:`Шторка → Wireless PowerShare / Battery Share.`},
  {id:29,platform:"android",tags:["dex","desktop","монитор"],title:"Desktop Mode / DeX",status:"possible",statusText:"Есть",desc:"Samsung DeX и нативный режим.",solution:`Samsung DeX. Другие — Desktop Mode при подключении к монитору. scrcpy с ПК.`},
  {id:30,platform:"android",tags:["split screen","разделённый экран"],title:"Разделённый экран",status:"possible",statusText:"Есть",desc:"С Android 7.",solution:`Недавние приложения → иконка → Разделить.`},

  // ===== Windows =====
  {id:40,platform:"windows",tags:["phone link","связь с телефоном"],title:"Связь с телефоном (Phone Link)",status:"possible",statusText:"Есть",desc:"Android и ограниченно iPhone.",solution:`Приложение «Связь с телефоном» на ПК + Link to Windows на Android.`},
  {id:41,platform:"windows",tags:["передать файл","localsend"],title:"Передача файлов",status:"possible",statusText:"Есть",desc:"LocalSend и другие.",solution:`LocalSend — лучший бесплатный вариант.`},
  {id:42,platform:"windows",tags:["буфер","clipboard"],title:"Облачный буфер обмена",status:"possible",statusText:"Есть",desc:"Синхронизация между устройствами Microsoft.",solution:`Параметры → Система → Буфер обмена. Win+V.`},
  {id:43,platform:"windows",tags:["scrcpy","управление android"],title:"Управление Android с ПК",status:"possible",statusText:"Есть",desc:"scrcpy — лучший вариант.",solution:`github.com/Genymobile/scrcpy + отладка по USB.`},
  {id:44,platform:"windows",tags:["виртуальные столы","snap","многозадачность"],title:"Виртуальные столы и Snap",status:"possible",statusText:"Есть",desc:"Мощная многозадачность.",solution:`Win+Tab, Snap Layouts, PowerToys FancyZones.`},
  {id:45,platform:"windows",tags:["windows hello","биометрия"],title:"Windows Hello",status:"possible",statusText:"Есть",desc:"Лицо или отпечаток.",solution:`Параметры → Учётные записи → Варианты входа.`},

  // ===== macOS =====
  {id:50,platform:"macos",tags:["continuity","handoff","airdrop","clipboard"],title:"Continuity / Handoff / Universal Clipboard",status:"possible",statusText:"Есть",desc:"Экосистема Apple.",solution:`Один Apple ID, Wi-Fi, Bluetooth, Handoff включён.`},
  {id:51,platform:"macos",tags:["sidecar","ipad монитор"],title:"iPad как второй монитор (Sidecar)",status:"possible",statusText:"Есть",desc:"Официально.",solution:`Control Center → Screen Mirroring → iPad.`},
  {id:52,platform:"macos",tags:["universal control","мышь","клавиатура"],title:"Universal Control",status:"possible",statusText:"Есть",desc:"Одна мышь на Mac и iPad.",solution:`Системные настройки → Дисплеи → Universal Control.`},

  // ===== Cross =====
  {id:60,platform:"cross",tags:["localsend","передать файл","кроссплатформ"],title:"Передача файлов между любыми устройствами",status:"possible",statusText:"Есть",desc:"LocalSend — лучший выбор.",solution:`localsend.org — Windows, macOS, Linux, Android, iOS. Одна сеть Wi-Fi.`},
  {id:61,platform:"cross",tags:["буфер","clipboard"],title:"Общий буфер обмена",status:"partial",statusText:"Частично",desc:"Зависит от экосистемы.",solution:`Apple Universal Clipboard, Microsoft облачный буфер, Pushbullet.`},
  {id:62,platform:"cross",tags:["уведомления","звонки на пк"],title:"Уведомления телефона на компьютере",status:"possible",statusText:"Есть",desc:"Phone Link, Continuity, KDE Connect.",solution:`Windows+Android: Phone Link. Mac+iPhone: Continuity.`},
  {id:63,platform:"cross",tags:["мышь","клавиатура","несколько устройств","barrier"],title:"Одна мышь и клавиатура на несколько устройств",status:"possible",statusText:"Есть",desc:"Несколько решений.",solution:`Logitech Flow, Mouse without Borders, Barrier/Synergy, Universal Control, Samsung Multi Control.`},
  {id:64,platform:"cross",tags:["зеркало","scrcpy","airplay"],title:"Зеркалирование экрана",status:"possible",statusText:"Есть",desc:"Много способов.",solution:`scrcpy (Android), AirPlay (Apple), Chromecast, Smart View.`},
  {id:65,platform:"cross",tags:["мессенджер","telegram","whatsapp"],title:"Единый мессенджер везде",status:"possible",statusText:"Есть",desc:"Telegram, WhatsApp, Signal, Discord.",solution:`Один аккаунт на телефоне, планшете, ПК и в браузере.`},

  // ===== Software =====
  {id:70,platform:"software",tags:["localsend"],title:"LocalSend",status:"possible",statusText:"Рекомендуется",desc:"Лучшая бесплатная передача файлов.",solution:`localsend.org — все платформы, без интернета, без регистрации.`},
  {id:71,platform:"software",tags:["scrcpy"],title:"scrcpy",status:"possible",statusText:"Рекомендуется",desc:"Управление Android с компьютера.",solution:`GitHub Genymobile/scrcpy. Отладка по USB.`},
  {id:72,platform:"software",tags:["powertoys"],title:"Microsoft PowerToys",status:"possible",statusText:"Рекомендуется",desc:"Утилиты для Windows.",solution:`FancyZones, PowerToys Run, Color Picker и др. Бесплатно.`},
  {id:73,platform:"software",tags:["altstore"],title:"AltStore",status:"possible",statusText:"Рекомендуется",desc:"Sideload на iOS.",solution:`altstore.io`},
  {id:74,platform:"software",tags:["kde connect"],title:"KDE Connect",status:"possible",statusText:"Рекомендуется",desc:"Связь Android с компьютером.",solution:`Уведомления, файлы, тачпад, медиа.`},

  // ===== Brands =====
  {id:80,platform:"brand",brand:"Samsung",tags:["samsung","galaxy","dex","smart switch","dual messenger","powershare","now bar"],title:"Samsung Galaxy — ключевые функции",status:"possible",statusText:"Много функций",desc:"Одна из самых богатых оболочек Android.",solution:`<ul><li><strong>DeX</strong> — режим ПК</li><li><strong>Smart Switch</strong> — лучший перенос данных</li><li><strong>Dual Messenger</strong> — два аккаунта</li><li><strong>Wireless PowerShare</strong> — обратная зарядка</li><li><strong>Now Bar / Good Lock</strong> — кастомизация</li><li><strong>Multi Control</strong> — мышь с телефона на ПК</li></ul>`},
  {id:81,platform:"brand",brand:"Xiaomi",tags:["xiaomi","hyperos","miui","dual apps","mi mover"],title:"Xiaomi / HyperOS — ключевые функции",status:"possible",statusText:"Много функций",desc:"Гибкая оболочка с большим числом настроек.",solution:`<ul><li>Dual Apps</li><li>Mi Mover — перенос данных</li><li>Вторая область / плавающие окна</li><li>Обратная зарядка на многих моделях</li><li>Тема и кастомизация через Темы</li></ul>`},
  {id:82,platform:"brand",brand:"Google",tags:["pixel","google","quick share","at a glance"],title:"Google Pixel — ключевые функции",status:"possible",statusText:"Чистый Android",desc:"Чистый Android + фишки Google.",solution:`<ul><li>Quick Share</li><li>At a Glance</li><li>Call Screen / Hold for Me</li><li>Долгие обновления</li><li>UWB на Pro-моделях</li></ul>`},
  {id:83,platform:"brand",brand:"Apple",tags:["apple","iphone","ipad","mac","continuity","airdrop"],title:"Apple — экосистема",status:"possible",statusText:"Сильная экосистема",desc:"Лучшая связка устройств между собой.",solution:`<ul><li>AirDrop, Handoff, Universal Clipboard</li><li>Continuity (звонки, SMS на Mac)</li><li>Sidecar, Universal Control</li><li>iCloud бэкап</li><li>Ограничения: нет sideload (кроме ЕС), нет split-screen на iPhone, нет обратной зарядки</li></ul>`},
  {id:84,platform:"brand",brand:"OnePlus",tags:["oneplus","oxygenos","parallel apps"],title:"OnePlus — ключевые функции",status:"possible",statusText:"Есть",desc:"OxygenOS близок к чистому Android.",solution:`Parallel Apps, быстрая зарядка, режим игры, хорошая многозадачность.`},
  {id:85,platform:"brand",brand:"Huawei",tags:["huawei","harmonyos","без гугл"],title:"Huawei / HarmonyOS",status:"partial",statusText:"Без Google",desc:"Нет сервисов Google на новых моделях.",solution:`AppGallery, Petal Search, своя экосистема. Многое решается через GBox / MicroG (на свой страх).`},
  {id:86,platform:"brand",brand:"Honor",tags:["honor","magicos"],title:"Honor — ключевые функции",status:"possible",statusText:"Есть",desc:"Отделился от Huawei, сервисы Google есть.",solution:`MagicOS, клонирование приложений, хорошая многозадачность, Yoyo-агент.`},
  {id:87,platform:"brand",brand:"Realme / Oppo / vivo",tags:["realme","oppo","vivo","coloros","funtouch"],title:"Realme / Oppo / vivo",status:"possible",statusText:"Есть",desc:"Общие корни (ColorOS / Funtouch).",solution:`App Cloner / Parallel Apps, быстрая зарядка, игровые режимы, много настроек экрана и батареи.`},
  {id:88,platform:"brand",brand:"Microsoft",tags:["microsoft","windows","phone link","powertoys"],title:"Microsoft / Windows",status:"possible",statusText:"Есть",desc:"Связка с телефонами и утилиты.",solution:`Phone Link, PowerToys, облачный буфер, Snap Layouts, Windows Hello.`},

  // ===== Частые настройки =====
  {id:90,platform:"android",tags:["автояркость","яркость","samsung","xiaomi"],title:"Отключить автояркость",status:"possible",statusText:"Есть",desc:"Частый запрос.",solution:`Настройки → Дисплей → убери галочку «Адаптивная яркость» / «Автояркость». На Samsung иногда дополнительно в Good Lock.`},
  {id:91,platform:"android",tags:["всегда включённый экран","aod","always on"],title:"Always On Display",status:"possible",statusText:"Есть",desc:"На большинстве AMOLED.",solution:`Настройки → Экран блокировки → Always On Display. Настраивается стиль часов и уведомлений.`},
  {id:92,platform:"android",tags:["навигация","жесты","кнопки"],title:"Жесты или кнопки навигации",status:"possible",statusText:"Есть",desc:"Можно переключать.",solution:`Настройки → Система → Жесты / Навигация → выбрать жесты или 3 кнопки.`},
  {id:93,platform:"ios",tags:["яркость","автояркость"],title:"Автояркость на iPhone",status:"possible",statusText:"Есть",desc:"Включается/выключается.",solution:`Настройки → Универсальный доступ → Дисплей и размер текста → Автояркость.`},
  {id:94,platform:"android",tags:["уведомления","не беспокоить","dnd"],title:"Режим «Не беспокоить»",status:"possible",statusText:"Есть",desc:"На всех системах.",solution:`Шторка → Не беспокоить. Можно настроить расписание и исключения.`},
  {id:95,platform:"windows",tags:["автозагрузка","startup"],title:"Управление автозагрузкой Windows",status:"possible",statusText:"Есть",desc:"Ускоряет запуск.",solution:`Ctrl+Shift+Esc → Автозагрузка. Или Параметры → Приложения → Автозагрузка.`}
];